import { createContext, useContext, useState, useCallback, type ReactNode } from 'react'

export type Lang = 'es' | 'en'

const STORAGE_KEY = 'briefscope:lang'

type Dict = Record<string, string>

const en: Dict = {
  // common
  'common.cancel': 'Cancel',
  'common.create': 'Create',
  'common.creating': 'Creating…',
  'common.save': 'Save',
  'common.saved': '✓ Saved',
  'common.loading': 'Loading…',
  'common.delete': 'Delete',
  'common.deleting': 'Deleting…',

  // units
  'unit.project': 'project',
  'unit.projects': 'projects',
  'unit.doc': 'doc',
  'unit.docs': 'docs',
  'unit.tokens': 'tokens',

  // project / sidebar
  'project.new': '+ New project',
  'project.newTitle': 'New project',
  'project.create': 'Create project',
  'project.namePlaceholder': 'Project name…',
  'project.none': 'No projects',
  'project.deleteTitle': 'Delete project',
  'project.deleteConfirm': 'Delete {name}?',
  'project.deleteWarning': 'All documents and conversations will be removed. This action cannot be undone.',
  'project.notFound': 'Project not found',
  'project.loading': 'Loading project…',

  // home
  'home.emptyTitle': 'No projects yet',
  'home.emptyDesc': 'Create your first project to start analyzing documents.',
  'home.projects': 'Projects',

  // documents panel
  'docs.tabDocs': 'DOCS',
  'docs.tabFiles': 'FILES',
  'docs.uploading': 'Uploading…',
  'docs.dropOrClick': 'Drag or click to upload',
  'docs.dropFilesOrClick': 'Drag files or click',
  'docs.empty': 'No documents.',
  'docs.emptyHint': 'Upload files to analyze.',
  'docs.emptyShort': 'No documents',
  'docs.loadingFiles': 'Loading files…',
  'docs.generatedEmpty': 'Files generated by the agent\nwill appear here.',
  'docs.download': 'Download {name}',
  'docs.deleteDocTitle': 'Delete document',
  'docs.deleteFileTitle': 'Delete file',
  'docs.deleteConfirm': 'Delete {name}?',
  'docs.deleteWarning': 'This action cannot be undone.',
  'docs.header': 'DOCUMENTS',

  // toggle
  'docs.hide': 'Hide documents',
  'docs.show': 'Show documents',

  // chat
  'chat.resetTitle': 'Clears the current conversation and starts over',
  'chat.reset': 'Reset conversation',
  'chat.loading': 'Loading conversation…',
  'chat.emptyPrompt': 'Ask a question about your documents',
  'chat.hint': 'Enter to send · Shift+Enter for a new line',
  'chat.generating': 'Generating response…',
  'chat.placeholder': 'Type your message… (Enter to send)',
  'chat.send': 'Send',
  'chat.attach': 'Attach documents to the project',
  'chat.analyzing': 'Analyzing request',

  // app shell banner
  'banner.configurePre': 'Set up your API key in ',
  'banner.configureLink': 'Settings',
  'banner.configurePost': ' to get started.',

  // settings
  'settings.loading': 'Loading settings…',
  'settings.back': 'Back',
  'settings.title': 'Settings',
  'settings.modeLocal': 'Local Mode — Ollama',
  'settings.modeCloud': 'Cloud Mode',
  'settings.ragTitle': 'RAG — Document Search',
  'settings.ragThreshold': 'Token Threshold',
  'settings.ragThresholdHint': 'Enable RAG above this limit',
  'settings.ragTopK': 'Top-K Results',
  'settings.historyTitle': 'History & Memory',
  'settings.compactAfter': 'Compact after N turns',
  'settings.compactHint': 'Old history is summarized to save tokens.',

  // cloud settings
  'cloud.provider': 'Provider',
  'cloud.locked': '🔒 fixed in this version',
  'cloud.providerHint': 'This version uses {provider} embeddings; the LLM is fixed to the same provider.',
  'cloud.model': 'Model',
  'cloud.apiKey': 'API Key',
  'cloud.configured': '✓ Configured',
  'cloud.keyPlaceholderReplace': '••••••••• (replace)',
  'cloud.deleteKey': 'Delete key',

  // local settings
  'local.host': 'Ollama Host',
  'local.activeModel': 'Active Model',
  'local.refresh': '↻ Refresh',
  'local.modelHint': 'The model is downloaded automatically if not installed.',
  'local.embedding': 'Embedding Model',
  'local.embeddingHint': 'Used for document search. Downloaded automatically on first use. Changing it invalidates indexed documents — re-upload them.',

  // language
  'lang.label': 'Language',
}

const es: Dict = {
  'common.cancel': 'Cancelar',
  'common.create': 'Crear',
  'common.creating': 'Creando…',
  'common.save': 'Guardar',
  'common.saved': '✓ Guardado',
  'common.loading': 'Cargando…',
  'common.delete': 'Eliminar',
  'common.deleting': 'Eliminando…',

  'unit.project': 'proyecto',
  'unit.projects': 'proyectos',
  'unit.doc': 'doc',
  'unit.docs': 'docs',
  'unit.tokens': 'tokens',

  'project.new': '+ Nuevo proyecto',
  'project.newTitle': 'Nuevo proyecto',
  'project.create': 'Crear proyecto',
  'project.namePlaceholder': 'Nombre del proyecto…',
  'project.none': 'Sin proyectos',
  'project.deleteTitle': 'Eliminar proyecto',
  'project.deleteConfirm': '¿Eliminar {name}?',
  'project.deleteWarning': 'Se borrarán todos los documentos y conversaciones. Esta acción no se puede deshacer.',
  'project.notFound': 'Proyecto no encontrado',
  'project.loading': 'Cargando proyecto…',

  'home.emptyTitle': 'Sin proyectos todavía',
  'home.emptyDesc': 'Crea tu primer proyecto para comenzar a analizar documentos.',
  'home.projects': 'Proyectos',

  'docs.tabDocs': 'DOCS',
  'docs.tabFiles': 'ARCHIVOS',
  'docs.uploading': 'Subiendo…',
  'docs.dropOrClick': 'Arrastra o haz clic para subir',
  'docs.dropFilesOrClick': 'Arrastra archivos o haz clic',
  'docs.empty': 'Sin documentos.',
  'docs.emptyHint': 'Sube archivos para analizar.',
  'docs.emptyShort': 'Sin documentos',
  'docs.loadingFiles': 'Cargando archivos…',
  'docs.generatedEmpty': 'Los archivos generados por el agente\naparecerán aquí.',
  'docs.download': 'Descargar {name}',
  'docs.deleteDocTitle': 'Eliminar documento',
  'docs.deleteFileTitle': 'Eliminar archivo',
  'docs.deleteConfirm': '¿Eliminar {name}?',
  'docs.deleteWarning': 'Esta acción no se puede deshacer.',
  'docs.header': 'DOCUMENTOS',

  'docs.hide': 'Ocultar documentos',
  'docs.show': 'Mostrar documentos',

  'chat.resetTitle': 'Borra la conversación actual y comienza desde cero',
  'chat.reset': 'Reiniciar conversación',
  'chat.loading': 'Cargando conversación…',
  'chat.emptyPrompt': 'Haz una pregunta sobre tus documentos',
  'chat.hint': 'Enter para enviar · Shift+Enter para nueva línea',
  'chat.generating': 'Generando respuesta…',
  'chat.placeholder': 'Escribe tu mensaje… (Enter para enviar)',
  'chat.send': 'Enviar',
  'chat.attach': 'Adjuntar documentos al proyecto',
  'chat.analyzing': 'Analizando solicitud',

  'banner.configurePre': 'Configura tu API key en ',
  'banner.configureLink': 'Configuración',
  'banner.configurePost': ' para comenzar.',

  'settings.loading': 'Cargando configuración…',
  'settings.back': 'Volver',
  'settings.title': 'Configuración',
  'settings.modeLocal': 'Modo Local — Ollama',
  'settings.modeCloud': 'Modo Cloud',
  'settings.ragTitle': 'RAG — Búsqueda en Documentos',
  'settings.ragThreshold': 'Umbral Tokens',
  'settings.ragThresholdHint': 'Activar RAG sobre este límite',
  'settings.ragTopK': 'Top-K Resultados',
  'settings.historyTitle': 'Historial y Memoria',
  'settings.compactAfter': 'Compactar tras N turnos',
  'settings.compactHint': 'El historial antiguo se resume para ahorrar tokens.',

  'cloud.provider': 'Proveedor',
  'cloud.locked': '🔒 fijado en esta versión',
  'cloud.providerHint': 'Esta versión usa embeddings de {provider}; el LLM queda fijado al mismo proveedor.',
  'cloud.model': 'Modelo',
  'cloud.apiKey': 'API Key',
  'cloud.configured': '✓ Configurada',
  'cloud.keyPlaceholderReplace': '••••••••• (reemplazar)',
  'cloud.deleteKey': 'Borrar key',

  'local.host': 'Ollama Host',
  'local.activeModel': 'Modelo Activo',
  'local.refresh': '↻ Actualizar',
  'local.modelHint': 'El modelo se descarga automáticamente si no está instalado.',
  'local.embedding': 'Modelo de Embedding',
  'local.embeddingHint': 'Se usa para la búsqueda en documentos. Se descarga automáticamente la primera vez. Cambiarlo invalida los documentos indexados — vuelve a subirlos.',

  'lang.label': 'Idioma',
}

const DICTS: Record<Lang, Dict> = { en, es }

function detectInitial(): Lang {
  try {
    const saved = localStorage.getItem(STORAGE_KEY)
    if (saved === 'es' || saved === 'en') return saved
  } catch { /* ignore */ }
  return 'en'
}

interface I18nValue {
  lang: Lang
  setLang: (l: Lang) => void
  t: (key: string, params?: Record<string, string | number>) => string
}

const I18nContext = createContext<I18nValue | null>(null)

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [lang, setLangState] = useState<Lang>(detectInitial)

  const setLang = useCallback((l: Lang) => {
    setLangState(l)
    try { localStorage.setItem(STORAGE_KEY, l) } catch { /* ignore */ }
  }, [])

  const t = useCallback(
    (key: string, params?: Record<string, string | number>) => {
      let str = DICTS[lang][key] ?? DICTS.en[key] ?? key
      if (params) {
        for (const [k, v] of Object.entries(params)) {
          str = str.replace(new RegExp(`\\{${k}\\}`, 'g'), String(v))
        }
      }
      return str
    },
    [lang],
  )

  return <I18nContext.Provider value={{ lang, setLang, t }}>{children}</I18nContext.Provider>
}

export function useTranslation(): I18nValue {
  const ctx = useContext(I18nContext)
  if (!ctx) throw new Error('useTranslation must be used within a LanguageProvider')
  return ctx
}
